backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Privacy Policy"
      name: "privacy_policy"
      file: "src/data/policy.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
  - label: 'Games'
    name: 'games'
    folder: 'src/data/games'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image', required: true }
      - { label: 'IOS Link', name: 'ios', widget: 'string' }
      - { label: 'Android Link', name: 'android', widget: 'string' }
      - { label: 'Description', name: 'short_description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
  - label: 'Apps'
    name: 'apps'
    folder: 'src/data/apps'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image', required: true }
      - { label: 'IOS Link', name: 'ios', widget: 'string' }
      - { label: 'Android Link', name: 'android', widget: 'string' }
      - { label: 'Description', name: 'short_description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
